### ISSUE TITLE
Add option to only store package-specific files in $out?

### ISSUE THREAD

**Issue by considerate** [purifix/purifix#28]
Currently each derivation will contain both the compiled files for the current package as well as all of the transitively compiled dependencies.

Do we want a mode where only the files that are unique to the current package in the output of a derivation? This would require combining the files when preparing a package but I think that should only be an issue for the top-level package.

Not having to store the compiled outputs many times over would make storing a package set much more lightweight.

**Comment by thomashoneyman** [comment]
👍 — much nicer for each package’s compiled output to only include that package’s modules and not dependencies and to aggregate them at the top level.
