### ISSUE TITLE
use purescript2nix as a translater in dream2nix for building PureScript projects

### ISSUE THREAD

**Issue by cdepillabout** [purifix/purifix#5]
I originally started working on `purescript2nix` as a backend for building PureScript projects with @DavHau's https://github.com/nix-community/dream2nix project.

I still think it would be nice to integrate `purescript2nix` into `dream2nix`, but I don't think I'd have the bandwidth to do it at least until #4 is solved.

Although someone interested could probably add a PureScript builder to `dream2nix` as an impure builder for now.

**Comment by considerate** [comment]
While making this repo more understandable by abiding by conventions specified in dream2nix sounds nice I haven’t seen that big uptake of dream2nix usage for it to warrant to base this project on that structure.

Nonetheless, I’d be willing to look at PRs attempting dream2nix compatibility and I think there are lessons to be learned by looking at that project when deciding what to do here.
