### ISSUE TITLE
unpackPhase error

### ISSUE THREAD

**Issue by deemp** [purifix/purifix#53]
Hi, @considerate! I'm trying to make a dev environment for a package https://github.com/deemp/gists/blob/master/purifixTrouble/flake.nix and it fails with

```console
error: builder for '/nix/store/zdx2dwjviwg70hp09b4ar1w076hcfvgy-develop-my-project.drv' failed with exit code 1;
       last 2 log lines:
       > unpacking sources
       > variable $src or $srcs should point to the source
       For full logs, run 'nix log /nix/store/zdx2dwjviwg70hp09b4ar1w076hcfvgy-develop-my-project.drv'.
error: 1 dependencies of derivation '/nix/store/fg3vhcc99327wabbdzzqp31dppyc1lh7-nix-shell-env.drv' failed to build
```

What can be the problem?

**Comment by considerate** [comment]
It looks like you’re including `app.develop` in `mkShell`. The expression `app.develop` already evaluates to a devShell so you don’t have to wrap it in a `mkShell` call.

If you want to add more things to the shell the preferred approach is to use `app.develop.overrideAttrs(old: { … })` and then extend the `nativeBuildInputs`.

**Comment by deemp** [comment]
Thank you! That was it.
